# -*- mode: Makefile; -*-

# This file is to be included by a GNU Makefile

# some common definitions

SYS = $(shell uname)

SHELL = /bin/sh
CC = gcc
#  maybe put CFLAGS here too ? 

CP = cp

# setup.sh should define an environment variable $prefix and $bindir

RM = rm
INSTALL = install

CC = gcc

