# -*- mode: Makefile; -*-
# $Id$

# some common definitions

SYS = $(shell uname)

SHELL = /bin/sh
CC = gcc
#  maybe put CFLAGS here too ? 

# prefix of the install:

# prefix = /usr/local
prefix = $(HOME)/$(SYS)

# where binaries go:
bindir = $(prefix)/bin


RM = rm
INSTALL = install

CC = gcc

