#!/bin/sh -x
#$Id$

# execute this file such that all the ancillary files end up, as symlinks, in
# the quilt src/ directory. It's should be enough to change the variable utils

utils=../../utils

ln -s $utils/alloc.c  ./
ln -s $utils/alloc.h ./
ln -s $utils/compat.c ./
ln -s $utils/compat.h ./
ln -s $utils/extra-math.c ./
ln -s $utils/extra-math.h ./
ln -s $utils/getargs.c ./
ln -s $utils/getargs.h ./
ln -s $utils/hash.c ./
ln -s $utils/hash.h ./
ln -s $utils/jacobi.c ./
ln -s $utils/jacobi.h ./
ln -s $utils/list.c ./
ln -s $utils/list.h ./
ln -s $utils/pdb.c ./
ln -s $utils/pdb.h ./
ln -s $utils/utils.c ./
ln -s $utils/utils.h ./
ln -s $utils/vecmat.h ./
