#!/bin/sh -x
#$Id$

src=~/src

ln -s $src/alloc.c  ./
ln -s $src/alloc.h ./
ln -s $src/compat.c ./
ln -s $src/compat.h ./
ln -s $src/extra-math.c ./
ln -s $src/extra-math.h ./
ln -s $src/getargs.c ./
ln -s $src/getargs.h ./
ln -s $src/hash.c ./
ln -s $src/hash.h ./
ln -s $src/jacobi.c ./
ln -s $src/jacobi.h ./
ln -s $src/list.c ./
ln -s $src/list.h ./
ln -s $src/pdb.c ./
ln -s $src/pdb.h ./
ln -s $src/utils.c ./
ln -s $src/utils.h ./
ln -s $src/vecmat.h ./
